import type { LeanToken, Artist, SnapshotMeta, Summary, MarketStats } from './types'

const BASE = `${import.meta.env.BASE_URL}data/`
const HIDDEN_FLAGS = new Set(['MALICIOUS', 'HIDDEN', 'REPORTED', 'AUTO_DETECT_COPY'])

/**
 * Typed on the flag alone, so it applies equally to a full catalog entry and to
 * a lean card from summary.json. The featured cards are filtered when that file
 * is built, but they are still re-checked here — moderation should not depend on
 * a data file having been generated correctly.
 */
export const isVisible = (t: { flag: string }) => !HIDDEN_FLAGS.has(t.flag)

let cache = new Map<string, Promise<unknown>>()

/** Test hook — clears memoized fetches. */
export const _resetCache = () => { cache = new Map() }

function getJson<T>(path: string): Promise<T> {
  const hit = cache.get(path)
  if (hit) return hit as Promise<T>

  let entry: Promise<unknown> | undefined
  entry = fetch(BASE + path)
    .then((res) => {
      if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`)
      return res.json()
    })
    .catch((err) => {
      // Evict failures. Memoizing a rejection means one transient error fetching, say,
      // tokens/slug-index.json makes every project deep link on the site answer
      // "not found" for the rest of the session, with no retry short of a reload.
      // Successes stay cached; only the failed attempt is forgotten.
      if (cache.get(path) === entry) cache.delete(path)
      throw err
    })

  cache.set(path, entry)
  return entry as Promise<T>
}

export const loadMeta = () => getJson<SnapshotMeta>('meta.json')
export const loadShard = (i: number) =>
  getJson<LeanToken[]>(`tokens/index-${String(i).padStart(3, '0')}.json`)
export const loadArtists = () => getJson<Artist[]>('artists/index.json')
export const loadTokensMap = () => getJson<Record<string, number[]>>('artists/tokens-map.json')

/** One artist on a collaborative project, with their revenue share if recorded. */
export interface Collaborator {
  id: string
  name: string | null
  share: number | null
}

/**
 * Who made the 553 projects whose catalog author is a contract, not a person.
 *
 * fxhash let artists mint through a shared collaboration contract, and the catalog
 * records that contract as the author — a KT1 address with no name. So those works
 * showed as made by nobody, appeared on none of their artists' pages, and could not
 * be found by anyone searching for that artist. The people are on chain, in the
 * contract's own storage; scripts/snapshot-collaborators.mjs reads them out.
 */
export interface Collaborations {
  generatedAt: string
  counts: { contracts: number; projects: number; artists: number }
  byProject: Record<string, { contract: string; collaborators: Collaborator[] }>
  byArtist: Record<string, number[]>
}

export const loadCollaborations = () => getJson<Collaborations>('collaborations.json')

/** A collaboration contract's address is a KT1, an artist's is a tz. */
export const isCollabContract = (id: string | null | undefined) => Boolean(id?.startsWith('KT1'))

/**
 * The people behind a project, or null if it is not a collaboration.
 *
 * Fetches nothing unless the author really is a contract, so the 98% of projects
 * with an ordinary artist never pay for this.
 */
export async function loadProjectArtists(
  projectId: number,
  authorId: string | null | undefined,
): Promise<Collaborator[] | null> {
  if (!isCollabContract(authorId)) return null
  const { byProject } = await loadCollaborations()
  return byProject[String(projectId)]?.collaborators ?? null
}

/**
 * Rank order, the archived id set, and headline counts in one small file.
 * Generated by scripts/build-summary.mjs so the grid can sort by collector
 * spending without fetching the 3 MB of market shards.
 */
export const loadSummary = () => getJson<Summary>('summary.json')

export async function loadAllTokens(): Promise<LeanToken[]> {
  const meta = await loadMeta()
  const shards = await Promise.all(Array.from({ length: meta.shardCount }, (_, i) => loadShard(i)))
  return shards.flat()
}

/** Which `tokens/index-NNN.json` shard holds this project, or undefined if unknown. */
async function shardIndexForSlug(slug: string): Promise<number | undefined> {
  const index = await getJson<Record<string, number>>('tokens/slug-index.json')
  return index[slug]
}

/**
 * Look a project up by slug — the single entry point every deep link goes through.
 *
 * Moderation is enforced *here*, not only where grids are built: a flagged project
 * (fxhash's own plagiarism/abuse flags) must be as unreachable from `#/token/<slug>`
 * as it is from the browse grid, or the promise made to users is a lie and the site
 * offers a "Run live" button on abusive code. A flagged slug resolves to not-found.
 */
export async function findTokenBySlug(slug: string): Promise<LeanToken | null> {
  const shardIdx = await shardIndexForSlug(slug)
  if (shardIdx === undefined) return null
  const shard = await loadShard(shardIdx)
  const token = shard.find((t) => t.slug === slug)
  return token && isVisible(token) ? token : null
}

/**
 * Project -> minted iteration ids, sharded to mirror `tokens/index-NNN.json`.
 * Captured from fxhash's own API, so it covers the launch-era tokens that carry
 * no `metadata.generatorUri` on chain and are therefore invisible to the TzKT join.
 */
export const loadIterationMap = (i: number) =>
  getJson<Record<string, string[]>>(`iterations/map-${String(i).padStart(3, '0')}.json`)

/**
 * The authoritative iteration ids for a project, as `FX{version}-{tokenId}`.
 *
 * Three outcomes, deliberately distinct — conflating any two of them recreates the
 * bug this exists to fix (claiming art was never minted when we simply cannot tell):
 *   - `string[]` (possibly empty) — we know; empty means genuinely never minted.
 *   - `null`                      — we do not know (no such project in the index).
 *   - rejection                   — we could not load the mapping at all.
 */
export async function loadIterationIds(slug: string, projectId: number): Promise<string[] | null> {
  const shardIdx = await shardIndexForSlug(slug)
  if (shardIdx === undefined) return null
  const map = await loadIterationMap(shardIdx)
  return map[String(projectId)] ?? null
}

/** `iterations/contracts.json`: the contract list, plus one index per project. */
interface IterationContracts {
  contracts: string[]
  byProject: Record<string, number>
}

/**
 * Which gentk contract each project's iterations live on, captured alongside the id
 * mapping. One small file for the whole catalog, so it is fetched once and memoized.
 */
export const loadIterationContracts = () => getJson<IterationContracts>('iterations/contracts.json')

/**
 * The gentk contract holding a project's iterations, or null when unknown.
 *
 * This cannot be inferred from anything else we hold. The `FX{n}` prefix of an
 * iteration id is the *issuer* version, not the contract; token id ranges overlap
 * across contracts; and all three contracts contain tokens without a `generatorUri`.
 * So the only honest answers are "this address" or null — callers must fall back
 * rather than guess, because a wrong contract renders another project's artwork.
 *
 * A project with no entry is one with no iterations at all; an out-of-range index
 * means the file is corrupt, which is likewise "we do not know", not `undefined`
 * smuggled into a TzKT URL.
 */
export async function loadIterationContract(projectId: number): Promise<string | null> {
  const { contracts, byProject } = await loadIterationContracts()
  const index = byProject[String(projectId)]
  if (index === undefined) return null
  return contracts[index] ?? null
}

/**
 * Captured seeds, chunked by tokenId in blocks of this size per gentk contract.
 * Must match CHUNK in scripts/snapshot-seeds.mjs.
 */
const SEED_CHUNK = 10000

interface SeedChunk {
  contract: number
  address: string
  from: number
  size: number
  seeds: Array<string | null>
  artifacts: Array<string | null>
}

/** What this repository holds for one minted iteration. */
export interface LocalIteration {
  seed: string | null
  /**
   * The query string and fragment fxhash itself used to drive the generator,
   * taken from the captured artifact URI — `?fxhash=…&fxiteration=…&fxminter=…`
   * and, for fx(params) projects, a trailing `#0x…` carrying the minter's chosen
   * parameters. Null when the artifact URI carried none.
   */
  query: string | null
  /**
   * The whole captured artifact URI, `ipfs://<cid>/?…`.
   *
   * This is the piece's address on IPFS, and it is held for every one of the
   * 1.8M iterations — which means a project whose code is *not* archived here can
   * still be played straight from a gateway, and stepped through, without asking
   * an indexer for anything. Null for a token that was never signed.
   */
  artifact: string | null
}

const loadSeedChunk = (contractIndex: number, chunk: number) =>
  getJson<SeedChunk>(`seeds/${contractIndex}/${String(chunk).padStart(4, '0')}.json`)

/**
 * A minted iteration's seed, read entirely from this repository.
 *
 * This is what lets an archived project run with no network at all: the seed is
 * the only thing besides the generator that a piece cannot be recreated without.
 * Tezos stores an IPFS pointer, never the seed itself; for most tokens the seed
 * does equal their mint operation's hash, but 9% have no on-chain copy at all —
 * see scripts/snapshot-seeds.mjs.
 *
 * Returns null rather than throwing for the two honest "no seed" cases: a project
 * whose contract we do not know, and a token that was minted but never signed, so
 * no seed was ever assigned to it.
 */
export async function loadProjectIteration(
  projectId: number,
  tokenId: number,
): Promise<LocalIteration> {
  const { byProject } = await loadIterationContracts()
  const contractIndex = byProject[String(projectId)]
  if (contractIndex === undefined) return { seed: null, query: null, artifact: null }
  const chunk = await loadSeedChunk(contractIndex, Math.floor(tokenId / SEED_CHUNK))
  // Indexed off the chunk's own `from`: one contract's ids start mid-chunk, so
  // `tokenId % SEED_CHUNK` would silently read the wrong slot for every token in it.
  const i = tokenId - chunk.from
  const artifact = chunk.artifacts?.[i] ?? null
  const mark = artifact ? artifact.indexOf('?') : -1
  return {
    seed: chunk.seeds[i] ?? null,
    // Everything from the '?' on, fragment included. Rebuilding this from the
    // seed alone would drop fxiteration, fxminter, and — for fx(params) pieces —
    // the parameters the minter chose, which are carried in the fragment and
    // exist nowhere else we captured.
    query: mark >= 0 ? artifact!.slice(mark) : null,
    artifact,
  }
}

/** Just the seed. See loadProjectIteration for what else is stored beside it. */
export async function loadProjectSeed(projectId: number, tokenId: number): Promise<string | null> {
  return (await loadProjectIteration(projectId, tokenId)).seed
}

/**
 * Projects per descriptions file. Must match CHUNK in
 * scripts/snapshot-descriptions.mjs.
 */
const DESCRIPTION_CHUNK = 250

/** Short keys because the file is mostly prose; see the snapshot script. */
interface DescriptionRow { d?: string | null; c?: string | null }

/** The artist's own words, which nothing else in this archive records. */
export interface ProjectText {
  /** What the project is, shown on its page. */
  description: string | null
  /** The text fxhash showed on each individual iteration. */
  iterationText: string | null
}

const EMPTY_TEXT: ProjectText = { description: null, iterationText: null }

/**
 * Artist-written text for a project.
 *
 * Chunked by project id, not by the slug index the other per-project files use, so
 * this needs no lookup first: a page holding a project id can name its own file.
 *
 * Resolves to empty rather than rejecting when there is nothing to show — a
 * missing description is a normal state, and it must never cost a visitor the page.
 */
export async function loadProjectText(projectId: number): Promise<ProjectText> {
  const chunk = String(Math.floor(projectId / DESCRIPTION_CHUNK)).padStart(4, '0')
  try {
    const rows = await getJson<Record<string, DescriptionRow>>(`descriptions/${chunk}.json`)
    const row = rows[String(projectId)]
    return { description: row?.d ?? null, iterationText: row?.c ?? null }
  } catch {
    return EMPTY_TEXT
  }
}

/** Market stats sharded to mirror `tokens/index-NNN.json`. */
const loadMarketShard = (i: number) =>
  getJson<Record<string, MarketStats | null>>(`market/stats-${String(i).padStart(3, '0')}.json`)

/**
 * A project's trading history, or null if it never traded.
 *
 * Loaded only when a project page opens: the full market data is 3 MB across 28
 * shards, and no other view needs a figure from it.
 */
export async function loadProjectMarketStats(
  slug: string,
  projectId: number,
): Promise<MarketStats | null> {
  const shardIdx = await shardIndexForSlug(slug)
  if (shardIdx === undefined) return null
  const shard = await loadMarketShard(shardIdx)
  return shard[String(projectId)] ?? null
}
