import { SANDBOX_SHIM } from './sandbox-shim.mjs'

// Building `_run.html`: the derived entry point the viewer loads instead of the
// artist's `index.html`.
//
// The artist's file is never modified. Preserving it byte-for-byte is the entire
// point of the archive, so the workaround lives in a file we wrote, under a name
// nobody will mistake for theirs, and anyone browsing the repository still finds
// the real generator at the obvious path.

/**
 * fxhash's legacy Math.pow patch, and the fingerprint of a document that needs it.
 *
 * Kept in step with LEGACY_PATCH_SCRIPT and needsLegacyPatch in src/lib/legacyPatch.ts,
 * which does the same job for a piece streamed from IPFS; runner-lib.test.mjs reads
 * both files and fails if the two literals drift apart. The reasoning is written out
 * in full over there — briefly: gentk v1 pieces seed their PRNG through
 * Math.pow(58, 11), whose true value is not representable as a double, and Math.pow
 * is implementation-approximated. One ULP changes three of the four sfc32 seeds, so
 * the piece renders as completely different art while looking perfectly healthy.
 *
 * The archived copies had no such patch anywhere: it was applied only on the IPFS
 * path, so 72 of the 420 archived projects ran from wrong seeds in the viewer and on
 * the gallery walls.
 */
const LEGACY_PATCH_SCRIPT =
  '<script id="fxhash-legacy-patch">(function(){Math.pow = (a,b) => (a===58 && b===11) ? 24986644000165536000 : a**b;})();</script>'

/**
 * The v1 b58dec, tolerant of minification. v2 folds iteratively and uses no
 * Math.pow at all, so this is exactly the fingerprint of a document with the bug,
 * and specific enough that ordinary Math.pow(x, 2) in artwork code does not trip it.
 */
const V1_SEED_POW = /Math\s*\.\s*pow\s*\(\s*alphabet\s*\.\s*length\s*,/

/** True only for a document carrying the buggy v1 fxhash seeding snippet. */
export function needsLegacyPatch(html) {
  return V1_SEED_POW.test(html) && /\bfxhash\b/.test(html)
}

const BANNER = [
  '<!--',
  '  Generated by scripts/build-runners.mjs — not part of the original artwork.',
  '',
  '  Identical to index.html except for the script below, which restores the few',
  '  browser APIs a sandboxed iframe takes away. See scripts/sandbox-shim.mjs.',
  "  The artist's file is untouched; run index.html for the original.",
  '-->',
].join('\n')

const LEGACY_BANNER = [
  '<!--',
  '  Generated by scripts/build-runners.mjs — not part of the original artwork.',
  '',
  "  This piece is a gentk v1 artifact, and seeds itself through Math.pow(58, 11) —",
  '  a value no double can hold exactly, and one engines are free to round their own',
  '  way. Left alone it would draw different art than it was minted as. The line',
  "  below is fxhash's own remedy, pinning that one result. See src/lib/legacyPatch.ts.",
  '-->',
].join('\n')

/**
 * How far into a document a structural tag may be and still be believed.
 *
 * `<head>` looks like an unmistakable landmark and is not one: two of the archived
 * projects (5 and 2675) carry a minified p5 that prints a page of its own, so the
 * first literal `<head>` in the file is 620,000 bytes in, inside a JavaScript
 * string — `i.print("<head>")`. Splicing there put a comment and a `<script>` tag
 * in the middle of a string literal, which is a syntax error, and put the shim
 * after the artwork it was meant to precede. A real opening tag is at the top of
 * the file; anything this far down is something else wearing the same clothes.
 */
const STRUCTURAL_WINDOW = 4096

/**
 * Insert the shim as early in the document as it can go.
 *
 * It has to run before any of the generator's own script, since it works by
 * patching prototypes and globals ahead of the code that uses them — and the
 * legacy Math.pow pin has to be parsed before the seeding snippet that calls it.
 *
 * `<html>` is preferred over `<head>` because it always comes first, and because
 * plenty of these documents open their fxhash snippet straight after it with no
 * `<head>` at all. A script placed there is not left dangling: the parser is in
 * "before head" mode, so it opens an implied `<head>` and puts the script in it.
 * Falling back the other way, and then to prepending, covers the hand-written
 * files — a few have no `<html>`, and a few have no structure to hook into.
 */
export function buildRunner(html) {
  // The legacy patch goes in first, so it is as early in the document as anything
  // can be. Both land ahead of the artist's own script either way — the fxhash
  // seeding snippet sits further down the file — but the ordering costs nothing
  // and the patch is the one with a hard "before it parses" requirement.
  const legacy = needsLegacyPatch(html) ? `${LEGACY_BANNER}\n${LEGACY_PATCH_SCRIPT}\n` : ''
  const tag = legacy + `${BANNER}\n<script>\n${SANDBOX_SHIM}\n</script>\n`
  // Whichever opens first, and only if it is near the top — see STRUCTURAL_WINDOW.
  const found = [/<html\b[^>]*>/i, /<head\b[^>]*>/i]
    .map((re) => html.match(re))
    .filter((m) => m && m.index < STRUCTURAL_WINDOW)
    .sort((a, b) => a.index - b.index)[0]
  // Unless the artist got in first. Project 16467 opens on its fxhash snippet at
  // byte 0 and does not reach <html> for another 1,372, so inserting at the tag
  // would put us behind a script we are supposed to precede. Prepending is not a
  // compromise here — the parser hoists a leading <script> into <head> regardless,
  // so it lands in the same place, only earlier.
  const firstScript = html.search(/<script\b/i)
  if (found && !(firstScript >= 0 && firstScript < found.index)) {
    const at = found.index + found[0].length
    return html.slice(0, at) + '\n' + tag + html.slice(at)
  }
  // No structure to hook into: the parser hoists a leading <script> into <head>
  // anyway, so prepending is equivalent for our purposes.
  return tag + html
}

/** The name of the derived entry point, alongside the artist's own. */
export const RUNNER_ENTRY = '_run.html'

/**
 * Substitute the shim and the gateway allow-list into the live wrapper.
 *
 * A streamed piece cannot be given a runner — the file is on a gateway, not here —
 * so public/live.html carries the shim as a *string* and splices it into whatever
 * it fetches. The placeholders are written as quoted string literals in the source
 * so that file stays valid and editable on its own; replacing the quotes along
 * with them is what turns each into a real literal.
 *
 * Throws rather than shipping a wrapper with a placeholder unfilled, since the
 * result would be a page that loads, looks fine, and silently protects nothing.
 * Both directions are checked: a placeholder that is missing (renamed in the
 * source, so the substitution quietly does nothing) and one that appears twice
 * (only the first would be filled).
 */
export function buildLiveWrapper(src, origins) {
  let out = src
  for (const [token, value] of [
    ['__SANDBOX_SHIM__', SANDBOX_SHIM],
    ['__GATEWAY_ORIGINS__', origins],
  ]) {
    const placeholder = `'${token}'`
    if (!out.includes(placeholder)) throw new Error(`live wrapper: no ${token} to substitute`)
    out = out.replace(placeholder, JSON.stringify(value))
    if (out.includes(token)) throw new Error(`live wrapper: ${token} appears more than once`)
  }
  return out
}
