import { SANDBOX_SHIM } from './sandbox-shim.mjs'

// Building `_run.html`: the derived entry point the viewer loads instead of the
// artist's `index.html`.
//
// The artist's file is never modified. Preserving it byte-for-byte is the entire
// point of the archive, so the workaround lives in a file we wrote, under a name
// nobody will mistake for theirs, and anyone browsing the repository still finds
// the real generator at the obvious path.

const BANNER = [
  '<!--',
  '  Generated by scripts/build-runners.mjs — not part of the original artwork.',
  '',
  '  Identical to index.html except for the script below, which restores the few',
  '  browser APIs a sandboxed iframe takes away. See scripts/sandbox-shim.mjs.',
  "  The artist's file is untouched; run index.html for the original.",
  '-->',
].join('\n')

/**
 * Insert the shim as early in the document as it can go.
 *
 * It has to run before any of the generator's own script, since it works by
 * patching prototypes and globals ahead of the code that uses them. Right after
 * `<head>` is the natural place; the fallbacks matter because plenty of these
 * files are hand-written and a few have no `<head>` at all.
 */
export function buildRunner(html) {
  const tag = `${BANNER}\n<script>\n${SANDBOX_SHIM}\n</script>\n`
  const head = html.match(/<head\b[^>]*>/i)
  if (head) {
    const at = head.index + head[0].length
    return html.slice(0, at) + '\n' + tag + html.slice(at)
  }
  const htmlTag = html.match(/<html\b[^>]*>/i)
  if (htmlTag) {
    const at = htmlTag.index + htmlTag[0].length
    return html.slice(0, at) + '\n' + tag + html.slice(at)
  }
  // No structure to hook into: the parser hoists a leading <script> into <head>
  // anyway, so prepending is equivalent for our purposes.
  return tag + html
}

/** The name of the derived entry point, alongside the artist's own. */
export const RUNNER_ENTRY = '_run.html'

/**
 * Substitute the shim and the gateway allow-list into the live wrapper.
 *
 * A streamed piece cannot be given a runner — the file is on a gateway, not here —
 * so public/live.html carries the shim as a *string* and splices it into whatever
 * it fetches. The placeholders are written as quoted string literals in the source
 * so that file stays valid and editable on its own; replacing the quotes along
 * with them is what turns each into a real literal.
 *
 * Throws rather than shipping a wrapper with a placeholder unfilled, since the
 * result would be a page that loads, looks fine, and silently protects nothing.
 * Both directions are checked: a placeholder that is missing (renamed in the
 * source, so the substitution quietly does nothing) and one that appears twice
 * (only the first would be filled).
 */
export function buildLiveWrapper(src, origins) {
  let out = src
  for (const [token, value] of [
    ['__SANDBOX_SHIM__', SANDBOX_SHIM],
    ['__GATEWAY_ORIGINS__', origins],
  ]) {
    const placeholder = `'${token}'`
    if (!out.includes(placeholder)) throw new Error(`live wrapper: no ${token} to substitute`)
    out = out.replace(placeholder, JSON.stringify(value))
    if (out.includes(token)) throw new Error(`live wrapper: ${token} appears more than once`)
  }
  return out
}
