import { CORS_SHIM } from './cors-shim.mjs'

// Building `_run.html`: the derived entry point the viewer loads instead of the
// artist's `index.html`.
//
// The artist's file is never modified. Preserving it byte-for-byte is the entire
// point of the archive, so the workaround lives in a file we wrote, under a name
// nobody will mistake for theirs, and anyone browsing the repository still finds
// the real generator at the obvious path.

/** Media a generator might put on a canvas, which is what tainting is about. */
const MEDIA = /\.(jpe?g|png|gif|webp|bmp|avif|svg|mp4|webm|ogv)$/i

const BANNER = [
  '<!--',
  '  Generated by scripts/build-runners.mjs — not part of the original artwork.',
  '',
  '  Identical to index.html except for the script below, which lets this piece',
  '  read its own images inside a sandboxed iframe. See scripts/cors-shim.mjs.',
  '  The artist\'s file is untouched; run index.html for the original.',
  '-->',
].join('\n')

/**
 * Whether a project needs a runner at all.
 *
 * The rule is "does it ship media", not "does it ship media *and* call a tainting
 * API". Scanning for the API is a guess about minified code — one missed spelling
 * and a project stays quietly broken — while the file list is a fact. Being wrong
 * the generous way costs 6 KB of duplicated HTML; being wrong the strict way costs
 * an artwork that does not render.
 */
export function needsRunner(files) {
  return files.some((f) => MEDIA.test(f))
}

/**
 * Insert the shim as early in the document as it can go.
 *
 * It has to run before any of the generator's own script, since it works by
 * patching prototypes ahead of the code that uses them. Right after `<head>` is
 * the natural place; the fallbacks matter because plenty of these files are
 * hand-written and a few have no `<head>` at all.
 */
export function buildRunner(html) {
  const tag = `${BANNER}\n<script>\n${CORS_SHIM}\n</script>\n`
  const head = html.match(/<head\b[^>]*>/i)
  if (head) {
    const at = head.index + head[0].length
    return html.slice(0, at) + '\n' + tag + html.slice(at)
  }
  const htmlTag = html.match(/<html\b[^>]*>/i)
  if (htmlTag) {
    const at = htmlTag.index + htmlTag[0].length
    return html.slice(0, at) + '\n' + tag + html.slice(at)
  }
  // No structure to hook into: the parser hoists a leading <script> into <head>
  // anyway, so prepending is equivalent for our purposes.
  return tag + html
}

/** The name of the derived entry point, alongside the artist's own. */
export const RUNNER_ENTRY = '_run.html'
